export const ADD_NEW_CUSTOMER = 'ADD_NEW_CUSTOMER';
export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT';
export const ADD_NEW_INVOICE = 'ADD_NEW_INVOICE';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_INVOICE = 'DELETE_INVOICE';
export const CUSTOMER_MODAL_SHOW = 'CUSTOMER_MODAL_SHOW';
export const CUSTOMER_MODAL_HIDE = 'CUSTOMER_MODAL_HIDE';